# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'RedditClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedditClient
  pod 'AlamofireImage'
  target 'RedditClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedditClientUITests' do
    # Pods for testing
  end

end
